---
- name: Create Nginx configuration
  template:
    src: ha.j2
    dest: "/etc/nginx/sites-available/{{ ha_master_hostname }}.conf"
  notify:
    - Restart Nginx

- name: Create symlink to Nginx config
  file:
    src: "/etc/nginx/sites-available/{{ ha_master_hostname }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ ha_master_hostname }}.conf"
    state: link
  notify:
    - Restart Nginx
