---
- name: Copy all pem files to masters
  copy:
    src: "{{ certdir }}/admin-{{ inventory_hostname }}.pem"
    dest: "{{ kube_cert_dir }}"
- name: Copy encryption-config.yaml to masters
  copy:
    src: "{{ certdir }}/encryption-config.yaml"
    dest: "{{ kube_dir }}"
