---
- name: Create necessary dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
     - "{{ kube_cert_dir }}"
- name: Copy certs to nodes
  copy:
    src: "{{ item }}"
    dest: "{{ kube_cert_dir }}"
  with_items:
    - "{{ certdir }}/ca.pem"
    - "{{ certdir }}/kube-proxy.pem"
    - "{{ certdir }}/kube-proxy-key.pem"
    - "{{ certdir }}/kubernetes.pem"
    - "{{ certdir }}/kubernetes-key.pem"
    - "{{ certdir }}/{{ inventory_hostname }}-key.pem"
    - "{{ certdir }}/{{ inventory_hostname }}.pem"
