---
- name: Copy certs to nodes
  copy:
    src: "{{ item }}"
    dest: "{{ kube_cert_dir }}"
  become: yes
  with_items:
    - "{{ certdir }}/ca.pem"
    - "{{ certdir }}/kube-proxy.pem"
    - "{{ certdir }}/kube-proxy-key.pem"
    - "{{ certdir }}/{{ inventory_hostname }}-key.pem"
    - "{{ certdir }}/{{ inventory_hostname }}.pem"
