---
- name: Create necessary dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
     - "{{ etcd_dir }}"
- name: Copy all certs to etcd-members
  copy:
    src: "{{ certdir }}/{{ item }}"
    dest: "{{ etcd_dir }}"
  with_items:
    - ca.pem
    - kubernetes.pem
    - kubernetes-key.pem
