---
- name: Copy ca.pem to etcd-members
  copy:
    src: "{{ certdir }}/ca.pem"
    dest: "{{ etcd_dir }}/"
    force: "{{ forcekeys | default('no') }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['etcd'] }}"
- name: Copy kubernetes.pem to etcd-members
  copy:
    src: "{{ certdir }}/kubernetes.pem"
    dest: "{{ etcd_dir }}/"
    force: "{{ forcekeys | default('no') }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['etcd'] }}"
- name: Copy kubernetes-key.pem to etcd-members
  copy:
    src: "{{ certdir }}/kubernetes-key.pem"
    dest: "{{ etcd_dir }}/"
    force: "{{ forcekeys | default('no') }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['etcd'] }}"
