---
- name: Check if master cert already exists
  stat:
    path: "{{ certdir }}/admin.pem"
  register: admin
- name: Generate csr for masters
  template:
    src: "admin-csr.json.j2"
    dest: "{{ certdir }}/admin-csr.json"
    mode: 0644
  when: not admin.stat.exists
- name: Generate master keys
  shell:
    cmd: |
      ./cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes admin-csr.json | ./cfssljson -bare admin
  args:
    chdir: "{{ certdir }}"
  when: not admin.stat.exists
