---
- name: Check if master cert already exists
  stat:
    path: "{{ certdir }}/admin.pem"
  register: admin
- name: Generate csr for masters
  copy:
    content: "{{ admin_csr | to_json }}"
    dest: "{{ certdir }}/admin-csr.json"
    mode: 0644
  when: not admin.stat.exists
- name: Generate master keys
  shell:
    cmd: |
      {{ cfssl_install_path }}/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes admin-csr.json | {{ cfssl_json_install_path }}/cfssljson -bare admin
  args:
    chdir: "{{ certdir }}"
  when: not admin.stat.exists
