---
- name: Check if encryption-config already exists
  stat:
    path: "{{ certdir }}/encryption-config.yaml"
  register: enc
- name: Generate encryption key
  shell:
    cmd: |
      head -c 32 /dev/urandom | base64
  register: encryption_key_cmd
  when: not enc.stat.exists
- name: Ensure encryption key fact
  set_fact:
    encryption_key: "{{ encryption_key_cmd.stdout }}"
  when: not enc.stat.exists
- name: Generate encryption-config.yaml
  template:
    src: "encryption-config.yaml.j2"
    dest: "{{ certdir }}/encryption-config.yaml"
    mode: 0644
  when: not enc.stat.exists
