---
- name: Check if api cert already exists
  stat:
    path: "{{ certdir }}/kubernetes.pem"
  register: api
- name: Save ips of all masters to var
  set_fact:
    api_ips: "{{ api_ips | default('') + hostvars[item]['ansible_host'] + ',' }}"
  with_items: "{{ groups['kubemasters'] | union (groups['etcd']) | unique  }}"
  when: not api.stat.exists
- debug:
    var: api_ips
- name: Generate csr for api
  template:
    src: "kubernetes-csr.json.j2"
    dest: "{{ certdir }}/kubernetes-csr.json"
    mode: 0644
  when: not api.stat.exists

- name: Generate kube-api keys
  shell: 
    cmd: |
      ./cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json \
        -hostname={{ kube_apiserver_ip }},{{ kube_apiserver_internal_ip }},{{ api_ips }}127.0.0.1,kubernetes.default,{{ cluster_name }} \
        -profile=kubernetes kubernetes-csr.json | ./cfssljson -bare kubernetes
  args:
    chdir: "{{ certdir }}"
    creates: "{{ certdir }}/kubernetes.pem"
  when: not api.stat.exists
