---
- name: Check if proxy cert already exists
  stat:
    path: "{{ certdir }}/kube-proxy.pem"
  register: proxy
- name: Generate csr for kube-proxy
  template:
    src: kube-proxy-csr.json.j2
    dest: "{{ certdir }}/kube-proxy-csr.json"
    mode: 0644
  when: not proxy.stat.exists
- name: Generate kube-proxy keys
  shell:
    cmd: |
      {{ cfssl_install_path }}/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-proxy-csr.json | {{ cfssl_json_install_path }}/cfssljson -bare kube-proxy
  args:
    chdir: "{{ certdir }}"
  when: not proxy.stat.exists
