---
- name: Check if CFSSLjson binary already installed
  stat:
    path: ./cfssljson
  register: cfssljson
- name: Download CFSSLjson binary
  get_url:
    url: "{{ cfssl_json_binary_url }}"
    dest: ./cfssljson
    mode: 0755
  when: not cfssljson.stat.exists
