---
- name: Check if CFSSL binary already installed
  stat:
    path: /usr/local/bin/cfssl
  register: cfssl
- name: Download CFSSL binary
  get_url:
    url: "{{ cfssl_binary_url }}"
    dest: /usr/local/bin/cfssl
    mode: 0755
  become: yes
  when: not cfssl.stat.exists
