---
- name: Check if CFSSLjson binary already installed
  stat:
    path: /usr/local/bin/cfssljson
  register: cfssljson
- name: Download CFSSLjson binary
  get_url:
    url: "{{ cfssl_json_binary_url }}"
    dest: /usr/local/bin/cfssljson
    mode: 0755
  become: yes
  when: not cfssljson.stat.exists
