---
- name: Update kubeconfig for admin context
  shell: |
        kubectl config set-cluster {{ cluster_name }} \
            --certificate-authority={{ certdir }}/ca.pem \
            --embed-certs=true \
            --server=https://{{ kube_master_host }}:{{ kube_master_port }} \
            --kubeconfig={{ kubeconfig_path }}
        kubectl config set-credentials {{ username }} \
            --client-certificate={{ certdir }}/admin.pem \
            --client-key={{ certdir }}/admin-key.pem \
            --embed-certs=true \
            --kubeconfig={{ kubeconfig_path }}
        kubectl config set-context {{ context }} \
            --cluster={{ cluster_name }} \
            --user={{ username }} \
            --kubeconfig={{ kubeconfig_path }}
        kubectl config use-context {{ context }} --kubeconfig={{ kubeconfig_path }}
  tags: ["admin_update_kubeconfig"]
