---
- name: Update kubeconfig for admin context
  shell: |
        kubectl config set-cluster {{cluster_name}} \
            --certificate-authority=./cert/{{cluster_name}}/ca.pem \
            --embed-certs=true \
            --server=https://{{kube_apiserver_ip}}:{{kube_apiserver_port}} \
            --kubeconfig={{ kubeconfig_path }}
        kubectl config set-credentials admin \
            --client-certificate={{ certdir }}/admin-kube-infra-01.rick.ai.pem \
            --client-key={{ certdir }}/admin-kube-infra-01.rick.ai-key.pem \
            --embed-certs=true \
            --kubeconfig={{ kubeconfig_path }}
        kubectl config set-context {{ context }} \
            --cluster={{cluster_name}} \
            --user=admin \
            --kubeconfig={{ kubeconfig_path }}
        kubectl config use-context {{ context }} --kubeconfig={{ kubeconfig_path }}
  tags: ["admin_update_kubeconfig"]
