- name: Check if kube-proxy binary already installed
  stat:
    path: "/usr/bin/kube-proxy"
  register: kubeproxy
- name: Download kube-proxy binary
  get_url:
    url: "{{ kube_proxy_url }}"
    dest: "/usr/bin/kube-proxy"
    mode: 0755
  when: not kubeproxy.stat.exists
