- name: "Create kube-proxy dirs if not exist"
  file:
    path: "/var/lib/kube-proxy"
    state: directory
- name: Ensure kubeproxy kubeconfig
  copy:
    src: "{{ kube_dir }}/kube-proxy.kubeconfig"
    dest: "/var/lib/kube-proxy/kubeconfig"
    remote_src: yes
- name: Ensure kubeproxy config
  template:
    src: "kube-proxy.conf.j2"
    dest: "/var/lib/kube-proxy/kube-proxy-config.yaml"
    mode: 0644
