- name: Install kube-proxy
  import_tasks: download_kube_proxy.yml
  tags: ['download-kube-proxy']

- name: Settigs for kube-proxy
  import_tasks: ensure_kube_proxy_settings.yml
  tags: ['ensure-kube-proxy-settigs']

- name: Check dirs for kubeproxy
  import_tasks: check_dirs.yml
  tags: ['check-dirs-kube-proxy']

- name: Ensure config for kube-proxy and kubeconfig
  import_tasks: ensure_config.yml
  tags: ['ensure-config-kube-proxy']

- name: Ensure systemd kube-proxy
  import_tasks: ensure_systemd_kube_proxy.yml
  tags: ['ensure-systemd-kube-proxy']

