---
- name: Install kube-proxy
  import_tasks: install.yml
  tags:
    - install_kube_proxy
    - ensure_systemd_kube_proxy
- name: Set up kube config for kube-proxy
  import_tasks: kube_config.yml
  tags: [ ensure_kube_proxy_settings ]
- name: Ensure config for kube-proxy and kubeconfig
  import_tasks: configure.yml
  tags: [ ensure_config_kube_proxy ]
- name: Start kube-proxy if not running yet
  service:
    name: kube-proxy
    enabled: yes
    state: started
  tags: [ check_systemd_kube_proxy ]
