---
- name: Create docker storage directory
  file:
    name: /storage
    state: directory
- name: Create docker configuration directory
  file:
    name: /etc/docker
    state: directory
- name: Copy Docker daemon config
  copy:
    content: "{{ docker_conf | to_nice_json }}"
    dest: /etc/docker/daemon.json
  notify: restart docker
