---
- name: Populate service facts
  service_facts:
- name: Fail if any of the services are not running
  fail:
    msg: Kubelet is not running
  when: "ansible_facts.services[item].state != 'running'"
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
