---
- name: Set environment up
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - src: kube-apiserver.env.j2
      dest: /etc/default/kube-apiserver
    - src: kube-controller-manager.env.j2
      dest: /etc/default/kube-controller-manager
    - src: kube-scheduler.env.j2
      dest: /etc/default/kube-scheduler
  notify: restart control plane

- name: Ensure systemd services
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - src: "kube-apiserver.service.j2"
      dest: "/etc/systemd/system/kube-apiserver.service"
    - src: "kube-controller-manager.service.j2"
      dest: "/etc/systemd/system/kube-controller-manager.service"
    - src: "kube-scheduler.service.j2"
      dest: "/etc/systemd/system/kube-scheduler.service"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Configure systemd services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
