---
- name: Ensure cluster roles config
  template:
    src: "clusterrole.yaml.j2"
    dest: "{{ kube_dir }}/clusterrole.yaml"
    mode: 0644
  run_once: True

- name: Ensure cluster roles binding
  template:
    src: "clusterrolebinding.yaml.j2"
    dest: "{{ kube_dir }}/clusterrolebinding.yaml"
    mode: 0644
  run_once: True

- name: Apply cluster roles
  shell: kubectl apply -f {{ kube_dir }}/clusterrole.yaml
  run_once: True

- name: sleep for 20 seconds and continue with play
  wait_for: timeout=20
  run_once: True

- name: Apply roles binding
  shell: kubectl apply -f {{ kube_dir }}/clusterrolebinding.yaml
  run_once: True
