- name: Ensure lo interface
  import_tasks: ensure_lo_interface.yml
  tags: ['ensure_lo_interface']

- name: Configure ExaBGP
  import_tasks: configure_exabgp.yml
  tags: ['config_exabgp']

- name: Install kube-apiserver
  import_tasks: install_kube_apiserver.yml
  tags: ['install_kube_apiserver']

- name: Install kube-scheduler
  import_tasks: install_kube_scheduler.yml
  tags: ['install_kube_scheduler']

- name: Install kube-controller-manager
  import_tasks: install_kube_controller_manager.yml
  tags: ['install_kube_controller_manager']

- name: Ensure direcotries
  import_tasks: ensure_kube_control_plane_directories.yml
  tags: ['ensure_kube_control_plane_directories']

- name: Ensure token file
  import_tasks: ensure_token_file.yml
  tags: ['ensure_token_file']

- name: Ensure systemd files
  import_tasks: ensure_kube_control_plane_systemd.yml
  tags: ['ensure_kube_control_plane_systemd']

- name: Check systemd files
  import_tasks: check_systemd.yml
  tags: ['check_systemd_kube_control_plane']

- name: Ensure cluster roles and binding files
  import_tasks: ensure_cluser_roles.yml
  tags: ['ensure_cluser_roles']

