---
- name: "Create cni config dir if not exist"
  file:
    path: "{{ cni_conf_dir }}"
    state: directory
- name: Ensure kubelet env vars
  template:
    src: kubelet.env.j2
    dest: "/etc/default/kubelet"
    mode: 0644
  notify: restart kubelet
- name: Ensure systemd unit file for kubelet
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
    mode: 0644
- name: Reload systemd
  systemd:
   daemon-reload: yes
- name: Stop systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
- name: Ensure kubelet systemd service
  service:
    name: kubelet
    state: started
    enabled: yes
