---
- name: Ensure kubelet env vars
  template:
    src: kubelet.env.j2
    dest: "{{ kube_dir }}/kubelet.env"
    mode: 0644
- name: Ensure systemd unit file for kubelet
  template:
    src: kubelet.service.j2
    dest: /lib/systemd/system/kubelet.service
    mode: 0644
- name: Ensure kubelet systemd service
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
