---
- name: Check for cni
  fail:
    msg: "Use calico or kuberouter or flannel for cni"
  when: cni not in ['calico', 'kuberouter', 'flannel']

- name: Ensure kube config for kubelet
  import_tasks: config.yml
  tags: ["kubelet_config"]

- name: Install kubelet
  import_tasks: install_kubelet.yml
  tags: ["install_kubelet"]

- name: Ensure calico
  import_tasks: calico.yml
  when: cni == "calico"
  tags: ["kubelet_calico"]

- name: Ensure kuberouter
  import_tasks: kuberouter.yml
  when: cni == "kuberouter"
  tags: ["kubelet_kuberouter"]

- name: Ensure flannel
  import_tasks: flannel.yml
  when: cni == "flannel"
  tags: ["kubelet_flannel"]

- name: Ensure systemd kubelet
  import_tasks: ensure_systemd_kubelet.yml
  tags: ["ensure_systemd_kubelet"]

- name: Check systemd kubelet
  import_tasks: check_systemd.yml
  tags: ["check_systemd_kubelet"]
