- name: Ensure coreDNS service
  template:
    src: "coredns_service.yaml.j2"
    dest: "{{ workdir_coredns.path }}/coredns_service.yaml"
    mode: 0644

- name: Apply coreDNS
  shell: "kubectl apply -f {{ workdir_coredns.path }}/coredns_service.yaml"
  run_once: True
