---
- name: Install coredns binary
  unarchive:
    src: "{{ coredns_link }}"
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: Ensure Corefile
  template:
    src: "Corefile.j2"
    dest: "/etc/Corefile"
    mode: 0644
  notify: ensure coredns systemd

- name: Ensure coreDNS service
  template:
    src: "coredns.service.j2"
    dest: "/etc/systemd/system/coredns.service"
    mode: 0644
  notify: ensure coredns systemd

- name: Stop systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
