---
- name: Register key
  shell: cat {{ kube_dir }}/ssl/kubernetes-key.pem | base64 -w 0
  register: kubernetes_key_pem

- name: Change kube-apiserver key
  shell: sed -i "s|__APISERVER_KEY__|{{ kubernetes_key_pem.stdout }}|g" {{ workdir_coredns.path }}/coredns.yaml

- name: Register cert
  shell: cat {{ kube_dir }}/ssl/kubernetes.pem | base64 -w 0
  register: kubernetes_pem

- name: Change kube-apiserver cert
  shell: sed -i "s|__APISERVER_CRT__|{{ kubernetes_pem.stdout }}|g" {{ workdir_coredns.path }}/coredns.yaml

- name: Register ca
  shell: cat {{ kube_dir }}/ssl/ca.pem | base64 -w 0
  register: ca_pem

- name: Change kube-apiserver ca
  shell: sed -i "s|__APISERVER_CA__|{{ ca_pem.stdout }}|g" {{ workdir_coredns.path }}/coredns.yaml

- name: Apply coreDNS
  shell: "kubectl apply -f {{ workdir_coredns.path }}/coredns.yaml"
  run_once: True
