---
- name: Ensure temporary directory to store data files
  tempfile:
    state: directory
    suffix: coredns
  register: workdir_coredns
  tags: ["ensure_workdir_coredns"]

- name: Ensure coreDNS config
  template:
    src: "coredns.yaml.j2"
    dest: "{{ workdir_coredns.path }}/coredns.yaml"
    mode: 0644
  tags: ["ensure_config_coredns"]

- name: CoreDNS | installation
  import_tasks: install.yml
  tags: ["install_coredns"]

- name: CoreDNS | Delete
  import_tasks: delete.yml
  tags: ["delete_coredns"]
