---
- name: Ensure temporary directory to store data files
  tempfile:
    state: directory
    suffix: coredns
  register: workdir_coredns
  tags: ["install_coredns"]
- name: Ensure coreDNS config
  template:
    src: "coredns.yaml.j2"
    dest: "{{ workdir_coredns.path }}/coredns.yaml"
    mode: 0644
  tags: ["install_coredns"]
- name: Apply coreDNS
  shell: "kubectl delete -f {{ workdir_coredns.path }}/coredns.yaml"
  run_once: True
  tags: ["install_coredns"]
