---
- name: CoreDNS | install host base
  import_tasks: install.yml
  tags: [install_coredns_host_base]

- name: CoreDNS | ensure k8s service
  import_tasks: k8s_service.yml
  tags:
    - ensure_service_coredns_host_base
    - never
