---
dependency:
  name: galaxy
  enabled: no
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance0
    box: ubuntu/bionic64
    box_version: 20190708.0.0
    memory: 512
    cpus: 1
    groups:
      - kubemasters
      - kubenodes
      - etcd
provisioner:
  name: ansible
  log: yes
  lint:
    name: ansible-lint
  connection_options:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_user: root
    ansible_become_method: sudo
    ansible_become: yes
verifier:
  name: testinfra
  lint:
    name: flake8
