---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance0
    box: debian/buster64
    box_version: 10.3.0
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  connection_options:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
    ansible_become_user: root
    ansible_become_method: sudo
verifier:
  name: testinfra
  lint:
    name: flake8
