---
dependency:
  name: galaxy
  enabled: no
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance0
    groups:
      - pci_dss
    box: ubuntu/bionic64
    box_version: 20190708.0.0
    memory: 2048
    cpus: 1
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  connection_options:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
    ansible_become_user: root
    ansible_become_method: sudo
verifier:
  name: testinfra
  lint:
    name: flake8
