- name: Ensure binary etcd and etcdclt
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: "etcd" , dest: "/usr/bin/etcd" }
    - { src: "etcdctl" , dest: "/usr/bin/etcdctl" }
