---
- name: Ensure ETCD systemd unit
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: 0644

- name: Reload Systemd
  systemd:
    daemon-reload: yes

- name: Ensure etcd env vars
  template:
    src: etcd.env.j2
    dest: /etc/default/etcd
    mode: 0644
  notify: restart etcd

- name: Ensure systemd ETCD service
  service:
    name: etcd
    state: started
    enabled: yes

