- name: bnx | Create rc.local service
  template:
    src: rc-local.service.j2
    dest: /lib/systemd/system/rc-local.service
    mode: "0644"

- name: bnx | Create rc.local with ethtools tuning
  template:
    src: rc.local.j2
    dest: /etc/rc.local
    mode: "0644"

- name: bnx | Ensure systemd rc.local service
  systemd:
    name: rc-local
    daemon_reload: yes
    state: restarted
    enabled: yes
