---
- name: Check if cri-o source already exists
  stat:
    path: "{{ build_crio_dir }}"
  register: crio_src
- name: Create tmp dirs if not exist
  file:
    path: "{{ build_crio_dir }}"
    state: directory
- name: Download cri-o source if no exists
  unarchive:
    src: "{{ crio_src_url }}"
    dest: "/tmp"
    remote_src: yes
    mode: 0755
  when: not crio_src.stat.exists
- name: Check if cri-o binaries builded
  stat:
    path: "{{ build_crio_dir }}/bin/crio"
  register: crio_binary
- name: Build cri-o binaries
  make:
    chdir: "{{ build_crio_dir }}"
    target: binaries
  when: not crio_binary.stat.exists
