---
- name: Check if crio conf already installed
  stat:
    path: /etc/crio/crio.conf
  register: crioconf
- name: Ensure crio config
  template:
    src: crio.conf.j2
    dest: /etc/crio/crio.conf
    mode: 0644
  when: not crioconf.stat.exists
