---
- name: Create crio folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "/etc/crio"
  - "/usr/local/libexec/crio"
  - "/etc/containers"
  - "/etc/containers/registries.d"
- name: Check if crio conf already installed
  stat:
    path: /etc/crio/crio.conf
  register: crioconf
- name: Ensure crio config
  template:
    src: crio.conf.j2
    dest: /etc/crio/crio.conf
    mode: 0644
  when: not crioconf.stat.exists
- name: Ensure policies configuration
  template:
    src: policy.json.j2
    dest: /etc/containers/policy.json
    mode: 0644
- name: Ensure registries configuration
  template:
    src: registries.conf.j2
    dest: /etc/containers/registries.conf
    mode: 0644
- name: Ensure storage configuration
  template:
    src: storage.conf.j2
    dest: /etc/containers/storage.conf
    mode: 0644
- name: Ensure default registries configuration
  template:
    src: default.j2
    dest: /etc/containers/registries.d/default
    mode: 0644
- name: Ensure seccomp config
  template:
    src: seccomp.json.j2
    dest: /etc/crio/seccomp.json
    mode: 0644
- name: Ensure crictl config
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    mode: 0644
