---
- name: Ensure systemd crio unit
  template:
    src: crio.service.j2
    dest: /lib/systemd/system/crio.service
    mode: 0644
- name: Ensure systemd crio service
  systemd:
    name: crio
    state: restarted
    daemon_reload: yes
    enabled: yes
