---
- name: Copy conmon binary
  copy:
    src: "conmon"
    dest: "/usr/local/bin/conmon"
    mode: 0755

- name: Copy pause binary
  copy:
    src: "pause"
    dest: "/usr/local/bin/pause"
    mode: 0755

- name: Copy crio binary
  copy:
    src: "crio"
    dest: "/usr/local/bin/crio"
    mode: 0755
