- name: Enable OverlayFS kernel module
  import_tasks: enable_overlay_fs_kernel.yml
  tags: ['enable_overlay_fs_kernel']

- name: Install CNI binaries
  import_tasks: install_cni_binaries.yml
  tags: ['install_cni_binaries']

- name: Install calico plugin CNI binaries
  import_tasks: install_calico_plugin.yml
  tags: ['install_calico_plugin']

- name: Install CRI-O binaries
  import_tasks: install_crio_binaries.yml
  tags: ['install_crio_binaries']

- name: Install runc binary
  import_tasks: install_runc.yml
  tags: ['install_runc']

- name: Install crictl binary
  import_tasks: install_crictl.yml
  tags: ['install_crictl']

- name: Ensure config
  import_tasks: ensure_crio_config.yml
  tags: ['ensure_crio_config']

- name: Remove config
  import_tasks: remove_crio_config.yml
  tags: ['remove_crio_config']

- name: Ensure systemd crio unit
  import_tasks: ensure_systemd_crio_unit.yml
  tags: ['ensure_systemd_crio_unit']

- name: Check systemd crio unit
  import_tasks: check_systemd_crio.yml
  tags: ['check_systemd_crio']
