---
- name: Remove policies configuration
  file:
    state: absent
    path: /etc/containers/policy.json
- name: Remove seccomp config
  file:
    state: absent
    path: /etc/crio/seccomp.json
- name: Remove crictl config
  file:
    state: absent
    path: /etc/crictl.yaml
- name: Remove crio config
  file:
    state: absent
    path: /etc/crio/crio.conf

