- name: install exabgp
  pip: name=exabgp version={{ exabgp_version }} state=present executable=pip2

- name: template exabgp.env
  template: src=exabgp.env.j2 dest=/etc/exabgp/exabgp.env
  notify:
    - remove pid
    - restart exabgp

- name: template exabgp.conf
  template: src=exabgp.conf.j2 dest=/etc/exabgp/exabgp.conf
  notify: reload exabgp

- name: check for systemd
  stat: path=/usr/bin/systemd
  register: systemd

- name: template init script
  template: src=exabgp.init.j2 dest=/etc/init.d/exabgp mode=0755 owner=root group=root

- name: enable and start exabgp
  service: name=exabgp enabled=yes state=started
