---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance0
    box: ubuntu/xenial64
    box_version: 20200814.0.0
    memory: 512
    cpus: 1
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 53, host: 5353"
      - "vm.network 'forwarded_port', guest: 9153, host: 9153"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  connection_options:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
    ansible_become_user: root
    ansible_become_method: sudo
verifier:
  name: testinfra
  lint:
    name: flake8
