---
- name: Ensure temporary directory to store data files
  tempfile:
    state: directory
    suffix: calico
  register: workdir

- name: Ensure tempate for calico over etcd
  template:
    src: "calico-etcd.yaml.j2"
    dest: "{{ workdir.path }}/calico-etcd.yaml"
    mode: 0644

- name: Register key
  shell: cat {{ kube_dir }}/ssl/kubernetes-key.pem | base64 -w 0
  register: kubernetes_key_pem

- name: Change etcd key
  shell: sed -i "s|__ETCD_KEY__|{{ kubernetes_key_pem.stdout }}|g" {{ workdir.path }}/calico-etcd.yaml

- name: Register cert
  shell: cat {{ kube_dir }}/ssl/kubernetes.pem | base64 -w 0
  register: kubernetes_pem

- name: Change etcd cert
  shell: sed -i "s|__ETCD_CRT__|{{ kubernetes_pem.stdout }}|g" {{ workdir.path }}/calico-etcd.yaml

- name: Register ca
  shell: cat {{ kube_dir }}/ssl/ca.pem | base64 -w 0
  register: ca_pem

- name: Change etcd ca
  shell: sed -i "s|__ETCD_CA__|{{ ca_pem.stdout }}|g" {{ workdir.path }}/calico-etcd.yaml

- name: Apply Calico definition on k8s
  command: 'kubectl apply -f {{ workdir.path }}/calico-etcd.yaml'
