---
- name: Download golang binary
  unarchive:
    src: "{{ golang_url }}"
    dest: /usr/local
    mode: 0755
    remote_src: yes
- name: Add the Go bin directory to the PATH environment variable for all users
  copy:
    src: go-bin.sh
    dest: /etc/profile.d
- name: Set GOPATH for all users
  copy:
    src: go-path.sh
    dest: /etc/profile.d
